// frontend/src/components/NotificationBell.jsx
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useNotifications } from '../../context/NotificationContext';
import { FaBell, FaTimes, FaHeart, FaComment, FaUserPlus, FaAt, FaShare, FaUsers } from 'react-icons/fa';

const NotificationBell = () => {
  const navigate = useNavigate();
  const [showDropdown, setShowDropdown] = useState(false);
  const dropdownRef = useRef(null);
  
  const {
    unreadCount,
    recentNotifications,
    fetchRecentNotifications,
    markAsRead,
    markAllAsRead,
    deleteNotification,
    isConnected
  } = useNotifications();

  const toggleDropdown = () => {
    setShowDropdown(!showDropdown);
    if (!showDropdown) {
      fetchRecentNotifications();
    }
  };

  const handleNotificationClick = async (notification) => {
    if (!notification.isRead) {
      await markAsRead(notification.id);
    }
    
    if (notification.actionUrl) {
      navigate(notification.actionUrl);
      setShowDropdown(false);
    }
  };

  const handleMarkAllAsRead = async () => {
    await markAllAsRead();
  };

  const handleDeleteNotification = async (id, event) => {
    event.stopPropagation();
    await deleteNotification(id);
  };

  const formatTime = (date) => {
    const now = new Date();
    const notificationDate = new Date(date);
    const diffInSeconds = Math.floor((now - notificationDate) / 1000);
    
    if (diffInSeconds < 60) return 'Just now';
    if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)}m ago`;
    if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)}h ago`;
    return `${Math.floor(diffInSeconds / 86400)}d ago`;
  };

  const getNotificationIcon = (type) => {
    const iconProps = { size: 16, className: "notification-type-icon" };
    
    switch (type) {
      case 'like':
        return <FaHeart {...iconProps} style={{ color: '#ef4444' }} />;
      case 'comment':
        return <FaComment {...iconProps} style={{ color: '#3b82f6' }} />;
      case 'follow':
        return <FaUserPlus {...iconProps} style={{ color: '#10b981' }} />;
      case 'mention':
        return <FaAt {...iconProps} style={{ color: '#8b5cf6' }} />;
      case 'share':
        return <FaShare {...iconProps} style={{ color: '#f59e0b' }} />;
      case 'friend_request':
        return <FaUsers {...iconProps} style={{ color: '#06b6d4' }} />;
      default:
        return <FaBell {...iconProps} style={{ color: '#6b7280' }} />;
    }
  };

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target) && 
          !event.target.closest('.notification-bell')) {
        setShowDropdown(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <div className="notification-bell-container" style={{ position: 'relative' }}>
      <button 
        onClick={toggleDropdown}
        className={`notification-bell btn btn-ghost btn-circle ${showDropdown ? 'btn-active' : ''}`}
        style={{
          position: 'relative',
        }}
      >
        <FaBell 
          size={20} 
          className="text-base-content"
          style={{
            animation: unreadCount > 0 ? 'bell-ring 1s ease-in-out' : 'none'
          }} 
        />
        {unreadCount > 0 && (
          <span 
            className="badge badge-error badge-sm absolute -top-1 -right-1"
            style={{
              fontSize: '10px',
              minWidth: '18px',
              height: '18px',
              lineHeight: '1'
            }}
          >
            {unreadCount > 99 ? '99+' : unreadCount}
          </span>
        )}
      </button>

      {showDropdown && (
        <div 
          ref={dropdownRef}
          className="notification-dropdown absolute top-12 right-0 w-96 max-h-96 bg-base-100 border border-base-300 rounded-lg shadow-xl z-50 overflow-hidden flex flex-col"
        >
          {/* Header */}
          <div className="p-4 border-b border-base-300 flex justify-between items-center">
            <h3 className="text-lg font-semibold text-base-content">
              Notifications
            </h3>
            <div className="flex gap-3 items-center">
              {unreadCount > 0 && (
                <button 
                  onClick={handleMarkAllAsRead}
                  className="btn btn-ghost btn-sm text-primary hover:text-primary-focus"
                >
                  Mark all as read
                </button>
              )}
              <button 
                onClick={() => {
                  navigate('/notifications');
                  setShowDropdown(false);
                }}
                className="btn btn-ghost btn-sm text-base-content/60 hover:text-primary"
              >
                See all
              </button>
            </div>
          </div>

          {/* Notifications List */}
          <div className="notifications-list flex-1 overflow-y-auto max-h-80">
            {recentNotifications && recentNotifications.length > 0 ? (
              recentNotifications.map((notification) => (
                <div 
                  key={notification.id}
                  className={`notification-item flex items-start p-3 cursor-pointer hover:bg-base-200 transition-colors relative ${
                    !notification.isRead ? 'bg-primary/10 border-l-2 border-l-primary' : ''
                  }`}
                  onClick={() => handleNotificationClick(notification)}
                >
                  {/* Icon */}
                  <div className="w-10 h-10 rounded-full bg-base-300 flex items-center justify-center mr-3 flex-shrink-0">
                    {getNotificationIcon(notification.type)}
                  </div>
                  
                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-base-content leading-relaxed m-0 break-words">
                      {notification.message}
                    </p>
                    <span className="text-xs text-base-content/60 mt-1 block">
                      {formatTime(notification.createdAt)}
                    </span>
                  </div>
                  
                  {/* Delete Button */}
                  <button 
                    onClick={(e) => handleDeleteNotification(notification.id, e)}
                    className="delete-btn btn btn-ghost btn-xs opacity-0 group-hover:opacity-100 hover:text-error"
                  >
                    <FaTimes size={12} />
                  </button>
                </div>
              ))
            ) : (
              <div className="p-10 text-center text-base-content/60">
                <FaBell 
                  size={48} 
                  className="text-base-content/30 mb-4 mx-auto" 
                />
                <p className="m-0">No new notifications</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Styles for animations */}
      <style jsx>{`
        @keyframes bell-ring {
          0%, 100% { transform: rotate(0deg); }
          10%, 30% { transform: rotate(-10deg); }
          20%, 40% { transform: rotate(10deg); }
        }
        
        .notification-item:hover .delete-btn {
          opacity: 1 !important;
        }
        
        @media (max-width: 640px) {
          .notification-dropdown {
            width: calc(100vw - 32px) !important;
            right: -16px !important;
          }
        }
      `}</style>
    </div>
  );
};

export default NotificationBell;

// frontend/src/components/NotificationBell.vue
<template>
  <div class="notification-bell-container">
    <button 
      @click="toggleDropdown" 
      class="notification-bell"
      :class="{ 'has-unread': unreadCount > 0 }"
    >
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="bell-icon">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
      </svg>
      <span v-if="unreadCount > 0" class="notification-badge">
        {{ unreadCount > 99 ? '99+' : unreadCount }}
      </span>
    </button>

    <transition name="dropdown">
      <div v-if="showDropdown" class="notification-dropdown" ref="dropdown">
        <div class="dropdown-header">
          <h3>Notifications</h3>
          <div class="header-actions">
            <button @click="markAllAsRead" v-if="unreadCount > 0" class="mark-all-read">
              Mark all as read
            </button>
            <router-link to="/notifications" class="see-all">
              See all
            </router-link>
          </div>
        </div>

        <div class="notifications-list" v-if="recentNotifications.length > 0">
          <div 
            v-for="notification in recentNotifications" 
            :key="notification.id"
            class="notification-item"
            :class="{ 'unread': !notification.isRead }"
            @click="handleNotificationClick(notification)"
          >
            <div class="notification-icon">
              <component :is="getNotificationIcon(notification.type)" />
            </div>
            
            <div class="notification-content">
              <p class="notification-message">{{ notification.message }}</p>
              <span class="notification-time">{{ formatTime(notification.createdAt) }}</span>
            </div>
            
            <button 
              @click.stop="deleteNotification(notification.id)" 
              class="delete-btn"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="delete-icon">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        
        <div v-else class="no-notifications">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="empty-icon">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
          </svg>
          <p>No new notifications</p>
        </div>
      </div>
    </transition>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { useNotificationStore } from '@/stores/notificationStore';
import { useRouter } from 'vue-router';
import { formatDistanceToNow } from 'date-fns';

const notificationStore = useNotificationStore();
const router = useRouter();
const showDropdown = ref(false);
const dropdown = ref(null);

const unreadCount = computed(() => notificationStore.unreadCount);
const recentNotifications = computed(() => notificationStore.recentNotifications);

const toggleDropdown = () => {
  showDropdown.value = !showDropdown.value;
  if (showDropdown.value) {
    notificationStore.fetchRecentNotifications();
  }
};

const handleNotificationClick = async (notification) => {
  if (!notification.isRead) {
    await notificationStore.markAsRead(notification.id);
  }
  
  if (notification.actionUrl) {
    router.push(notification.actionUrl);
    showDropdown.value = false;
  }
};

const markAllAsRead = async () => {
  await notificationStore.markAllAsRead();
};

const deleteNotification = async (id) => {
  await notificationStore.deleteNotification(id);
};

const formatTime = (date) => {
  return formatDistanceToNow(new Date(date), { addSuffix: true });
};

const getNotificationIcon = (type) => {
  const icons = {
    like: 'HeartIcon',
    comment: 'ChatIcon',
    follow: 'UserAddIcon',
    mention: 'AtSymbolIcon',
    share: 'ShareIcon',
    friend_request: 'UsersIcon'
  };
  return icons[type] || 'BellIcon';
};

const handleClickOutside = (event) => {
  if (dropdown.value && !dropdown.value.contains(event.target) && 
      !event.target.closest('.notification-bell')) {
    showDropdown.value = false;
  }
};

onMounted(() => {
  document.addEventListener('click', handleClickOutside);
  notificationStore.requestNotificationPermission();
});

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside);
});
</script>

<style scoped>
.notification-bell-container {
  position: relative;
}

.notification-bell {
  position: relative;
  background: none;
  border: none;
  cursor: pointer;
  padding: 8px;
  border-radius: 50%;
  transition: background-color 0.3s;
}

.notification-bell:hover {
  background-color: rgba(0, 0, 0, 0.05);
}

.bell-icon {
  width: 24px;
  height: 24px;
  color: #333;
}

.notification-bell.has-unread .bell-icon {
  animation: bell-ring 1s ease-in-out;
}

@keyframes bell-ring {
  0%, 100% { transform: rotate(0deg); }
  10%, 30% { transform: rotate(-10deg); }
  20%, 40% { transform: rotate(10deg); }
}

.notification-badge {
  position: absolute;
  top: 0;
  right: 0;
  background-color: #ef4444;
  color: white;
  font-size: 11px;
  font-weight: bold;
  padding: 2px 5px;
  border-radius: 10px;
  min-width: 18px;
  text-align: center;
}

.notification-dropdown {
  position: absolute;
  top: calc(100% + 10px);
  right: 0;
  width: 380px;
  max-height: 480px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.15);
  z-index: 1000;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.dropdown-header {
  padding: 16px;
  border-bottom: 1px solid #e5e7eb;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.dropdown-header h3 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
}

.header-actions {
  display: flex;
  gap: 12px;
  align-items: center;
}

.mark-all-read {
  background: none;
  border: none;
  color: #3b82f6;
  font-size: 14px;
  cursor: pointer;
  font-weight: 500;
}

.mark-all-read:hover {
  text-decoration: underline;
}

.see-all {
  color: #6b7280;
  text-decoration: none;
  font-size: 14px;
}

.see-all:hover {
  color: #3b82f6;
}

.notifications-list {
  flex: 1;
  overflow-y: auto;
  max-height: 380px;
}

.notification-item {
  display: flex;
  align-items: start;
  padding: 12px 16px;
  cursor: pointer;
  transition: background-color 0.2s;
  position: relative;
}

.notification-item:hover {
  background-color: #f9fafb;
}

.notification-item.unread {
  background-color: #eff6ff;
}

.notification-item.unread::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 3px;
  background-color: #3b82f6;
}

.notification-icon {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background-color: #f3f4f6;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 12px;
  flex-shrink: 0;
}

.notification-content {
  flex: 1;
  min-width: 0;
}

.notification-message {
  margin: 0;
  font-size: 14px;
  color: #1f2937;
  line-height: 1.5;
  word-wrap: break-word;
}

.notification-time {
  font-size: 12px;
  color: #9ca3af;
  margin-top: 4px;
  display: inline-block;
}

.delete-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px;
  opacity: 0;
  transition: opacity 0.2s;
}

.notification-item:hover .delete-btn {
  opacity: 1;
}

.delete-icon {
  width: 16px;
  height: 16px;
  color: #9ca3af;
}

.delete-btn:hover .delete-icon {
  color: #ef4444;
}

.no-notifications {
  padding: 40px;
  text-align: center;
  color: #9ca3af;
}

.empty-icon {
  width: 48px;
  height: 48px;
  margin: 0 auto 16px;
  color: #d1d5db;
}

.dropdown-enter-active,
.dropdown-leave-active {
  transition: all 0.3s ease;
}

.dropdown-enter-from,
.dropdown-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

@media (max-width: 640px) {
  .notification-dropdown {
    width: calc(100vw - 32px);
    right: -8px;
  }
}
</style>
